apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hxjb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hxjb
    app.kubernetes.io/part-of: tkrw-pr712-0075-0064-app
  name: devfile-sample-hxjb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-hxjb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-hxjb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-hxjb@sha256:35ee8b42ee940699721e2e966d48571a628f1d0ce6e4694ab2f12c6c864485b4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
